SELECT * from customer LIMIT 10;

-- Q1. What is the total revenue generated by male vs female customers?

SELECT gender, sum(purchase_amount) as revenue 
from customer
group by gender;

-- Q2. Which customer used discount but still spent more than average purchase amount?

SELECT customer_id, purchase_amount from customer 
WHERE discount_applied='YES' 
AND purchase_amount>=(SELECT avg(purchase_amount) from customer);

-- Q3. Which are the top 5 product with highest average review rating?

SELECT item_purchased, round(avg(review_rating),2) as average_product_rating 
from customer
GROUP BY item_purchased 
ORDER BY average_product_rating DESC
limit 5;

-- Q4. Compare the average product amount between standard and express shipping?

SELECT shipping_type, round(avg(purchase_amount),2) from customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers?

SELECT subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer 
GROUP BY subscription_status 
ORDER BY total_revenue, avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased, round(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into new, returning, and loyal based on their total no. of previous purchases, and show the count of each segment?

WITH customer_type as(
SELECT customer_id, previous_purchases,
CASE 
WHEN previous_purchases=1 THEN 'New'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
ELSE 'Loyal'
END as customer_segment
from customer
)
SELECT customer_segment, count(*) as 'No of Customers'
from customer_type
GROUP BY customer_segment;

-- Q8. What is the top 3 most purchased product within each category?

WITH item_counts as (
SELECT category, item_purchased, count(customer_id) as total_order,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY count(customer_id) DESC) as item_rank
from customer
GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_order
from item_counts
WHERE item_rank<=3;

-- Q9. Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
count(customer_id) as repeat_buyers
from customer
WHERE previous_purchases>5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?

SELECT age_group, sum(purchase_amount) as total_revenue 
from customer
GROUP BY age_group
ORDER BY total_revenue DESC;